### ISSUE TITLE
Morning Session Team - P2P CR - #1

### ISSUE THREAD

**Issue by OmarRamoun** [dicodiaz/portfolio-first-draft#10]
Morning Session Peer to Peer Code Review

**Comment by OmarRamoun** [comment]
Hi @dicodiaz , :wave:

You have done an amazing job :clap::clap::clap:
However, there are some issues that you still need to work on

### To highlight

:heavy_check_mark: Very descriptive PR title
:heavy_check_mark: Very descriptive PR description
:heavy_check_mark: Very descriptive README
:heavy_check_mark: Super descriptive commit messages
:heavy_check_mark: Use of semantic HTML

However, there are some issues that you still need to work on

### Required Changes ♻️

- [x] it would be better to remove commented code entirely from the code base and use git history to checkout old code

https://github.com/dicodiaz/Portfolio/blob/bd7cf8d5381f5dacc36eab87a332b4211bbfabe3/css/styles.css#L302-L320

### Optional Suggestions :left_speech_bubble: 

- [x] [Optional] please, it would be better to add interactive animations to all social media bars on the website.
- [x] [Optional] if you can add interactive animation feedback to the navigation menu, that would be better.

Cheers and happy coding, :+1: :wave:

**Comment by nachosala89** [comment]
You do it great with the pull request description :smile:. However, I leave you some issues I found that maybe you could consider to improve your project:
- [x] When every card of the projects section is hovered, it overlaps the Navbar.
- [x] Your Readme.md file seems outdated since the title says "Mobile version" and you already have the Desktop version too.

**Comment by dicodiaz** [comment]
Applied every suggested change. Thank you very much, guys!
